application: intense-guru-130919
version: 1
runtime: python27
api_version: 1
threadsafe: true
module: default

handlers:
- url: /stylesheets
  static_dir: stylesheets

- url: /.* 
  script: helloworld.app

libraries:
- name: jinja2
  version: latest

